# Generated by Django 3.2.13 on 2022-07-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'responsavel',
                'verbose_name_plural': 'responsaveis',
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=40, verbose_name='descricao')),
            ],
            options={
                'verbose_name': 'sistema',
                'verbose_name_plural': 'sistemas',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subsistema', models.CharField(blank=True, max_length=40, null=True, verbose_name='subsistema')),
                ('descricao', models.CharField(max_length=40, verbose_name='descricao')),
                ('detalhes', models.TextField(verbose_name='detalhes')),
                ('periodicidade', models.IntegerField(verbose_name='periodicidade')),
                ('tipo_periodo', models.SmallIntegerField(choices=[(1, 'dias'), (7, 'semanas'), (30, 'meses'), (360, 'anos')], verbose_name='tipo de periodo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.responsavel', verbose_name='responsavel')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.sistema', verbose_name='sistema')),
            ],
            options={
                'verbose_name': 'procedimento',
                'verbose_name_plural': 'procedimentos',
            },
        ),
    ]
